### ISSUE TITLE
Listing config options directly after installing with pipx crashes

### ISSUE THREAD

**Issue by cubix-netizen** [plotski/upsies#1]
Upsies version: 1e0360f33af8be5774ca76c961e21c7197ab6101

Command that I ran: `upsies set`, directly after installing latest commit with pipx

OS: Gentoo Linux with kernel version 5.10.27

Traceback:
`Traceback (most recent call last):
  File "/mnt/mpathe/rhyjoo/.local/pipx/venvs/upsies/lib/python3.8/site-packages/upsies/uis/tui/main.py", line 25, in _main
    application_shutdown(cmd.config)
  File "/mnt/mpathe/rhyjoo/.local/pipx/venvs/upsies/lib/python3.8/site-packages/upsies/__init__.py", line 27, in application_shutdown
    fs.limit_directory_size(
  File "/mnt/mpathe/rhyjoo/.local/pipx/venvs/upsies/lib/python3.8/site-packages/upsies/utils/fs.py", line 91, in limit_directory_size
    while size(filepaths) > max_total_size:
  File "/mnt/mpathe/rhyjoo/.local/pipx/venvs/upsies/lib/python3.8/site-packages/upsies/utils/fs.py", line 82, in size
    return sum(file_size(f) for f in filepaths)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

**Comment by plotski** [comment]
Thanks. Should be fixed.
